### ISSUE TITLE
Feat: Redirect to vault page when searching by address

### ISSUE THREAD

**Issue by murderteeth** [yearn/seafood#146]
Enter a vault, strategy, or want address in the vault dashboard's search box, then filter the vaults list accordingly.

like this, but without the redirect:
![image](https://user-images.githubusercontent.com/89237203/219202988-9b31dd94-d5c1-4d43-92e3-abc1ac8e9665.png)

**Comment by udhaykumarbala** [comment]
Hi @murderteeth , can i work on this

**Comment by murderteeth** [comment]
Thanks @udhaykumarbala! I'm here if you have questions

**Comment by udhaykumarbala** [comment]
Hi @murderteeth,
![CleanShot 2023-07-15 at 15 03 32@2x](https://github.com/yearn/seafood/assets/24606613/1e939762-ad89-4443-b53e-dada96d2b891)
 This is the search box, i need to apply the changes, right ?

**Comment by murderteeth** [comment]
@udhaykumarbala yes, that's correct

**Comment by udhaykumarbala** [comment]
Hi @murderteeth, sorry for the delay. please review the PR when you are available
Thank you

**Comment by murderteeth** [comment]
great work @udhaykumarbala, thank you 🙏
