### ISSUE TITLE
Feat: Show a warning when prod vaults have a zero deposit limit

### ISSUE THREAD

**Issue by murderteeth** [yearn/seafood#148]
for example
![image](https://user-images.githubusercontent.com/89237203/223811914-1325059b-3ce7-425c-93a8-78116e01e3e3.png)

**Comment by ArslanYM** [comment]
How can we approach this problem?

**Comment by murderteeth** [comment]
> How can we approach this problem?

I think highlighting the "Deposit Limit" text would be a good start. But I'd also like you to make suggestions. What do you think?
