### ISSUE TITLE
bug: when on network other than eth address click doesnt work

### ISSUE THREAD

**Issue by 0xBasically** [yearn/seafood#181]
![image](https://github.com/yearn/seafood/assets/131375535/6d2646ab-3f5f-4994-9857-114abdd83fa4)
trying to click on the address to go to basescan or arbiscan doesnt seem to work well on all other networks. 
I noticed base and arbi but opti seems to be fine. 
It does seem to work on this page tho oddly enough 
![image](https://github.com/yearn/seafood/assets/131375535/e7a84af5-bffb-415e-a916-f743a55c5d0b)

**Comment by murderteeth** [comment]
verified no longer an issue
